name: Build and Push Docker Image on commit to v6-rewrite

env:
    RELEASE_VERSION:

on:
    push:
        branches:
            - v6-rewrite

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: mariusbegby/cadence:v6-beta
