name: Release Notes PR

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  release-type: node
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
                  target-branch: ${{ github.ref_name }}

